services:
  3307live:
    container_name: 3307live
    restart: unless-stopped
    env_file: stack.env
    volumes:
      - /path/to/vod/storage:/data/videos # update VIDEOS_DIR env var
      - ./temp:/data/temp # update TEMP_DIR env var
      - ./logs:/data/logs # queue logs
      - ./config:/data/config # config and other miscellaneous files
    ports:
      - 4800:4000
    healthcheck:
      test: curl --fail http://localhost:4000/health || exit 1
      interval: 60s
      retries: 5
      start_period: 60s
      timeout: 10s

