version: "3"

tasks:
  swag:
    preconditions:
      - go install github.com/swaggo/swag/cmd/swag@latest
    cmds:
      - swag init -g cmd/server/main.go
  init:
    cmds:
      - mkdir -p ./dev/vods
      - mkdir -p ./dev/logs
      - mkdir -p ./dev/data
  ent_generate:
    cmds:
      - go run -mod=mod entgo.io/ent/cmd/ent generate --feature sql/upsert ./ent/schema
